### ISSUE TITLE
Can't build the app on mac

### ISSUE THREAD

**Issue by kseniiastativka** [arnonax/mvcforum#1]
Are there are any instructions on how to build the app on Mac? I've tried to build with Visual Studio (v 8.1.1) and receipt this error `/Users/Kseniia/.nuget/packages/buildwebcompiler/1.11.375/build/BuildWebCompiler.targets(9,9): Error: Cannot find the specified file (MvcForum.Web) `

Thank you in advance

**Comment by arnonax** [comment]
Hi Kseniia,
I understand that you're trying to build the project using Visual Studio
for Mac. AFAIU, Visual Studio for Mac is not a fully featured version of
Visual Studio and does not support the .net framework (only Xamarin and
.net core IIRC). In order to build and run the project you'll need a
Windows OS, which you can run on a Mac using Parallels.

בתאריך שבת, 29 ביוני 2019, 20:42, מאת Kseniia Stativka ‏<
notifications@github.com>:

**Comment by kseniiastativka** [comment]
Hi Arnon, thank you for your prompt reply!
